language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 5.5
          services:
              - docker
        - php: 5.6
          services:
              - docker
        - php: 7.0
          services:
              - docker
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=2.7.*
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=2.8.*
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
          services:
              - docker

before_install:
    - docker run -d --name boulder --net host acmephp/testing-ca
    - phpenv config-rm xdebug.ini
#    - composer global require hirak/prestissimo
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - docker logs boulder
    - docker run --rm --net host martin/wait -c localhost:4000 -t 120
    - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS
    - rm -rf features/fixtures/TestApp/cache/*
    - features/fixtures/TestApp/console acmephp:server:start

script:
    - bin/phpunit
    - bin/behat --format progress
