language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 5.5
          services:
              - docker
        - php: 5.6
          services:
              - docker
        - php: 7.0
          services:
              - docker
        - php: hhvm
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=2.7.*
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=2.8.*
          services:
              - docker
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
          services:
              - docker

before_install:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then docker run -d --name boulder --net host acmephp/testing-ca; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update
    - composer global require hirak/prestissimo
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then rm -rf features/fixtures/TestApp/cache/*; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then features/fixtures/TestApp/console acmephp:server:start; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then docker run --rm --net host martin/wait -c localhost:4000 -t 120; fi;

script:
    - bin/phpunit
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then bin/behat --format progress; fi;
